require('plugins')
require('settings')
require('mappings')
require('treesitter-config')
-- require('coc-config')
require('gitsigns-config')
require('nvimTree-config')
require('whichkey-config')
require('telescope-config')
require('neoclip-config')
require('lsp')
require('trouble-config')
require('bufferline-config')
require('diffview-config')
--test delete later
